
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

jwt:
  secret: ${JWT_KEY}
  lifetime: ${JWT_LIFETIME}

minio:
  url: ${MINIO_URL}
  get-bucket: ${MINIO_GET_BUCKET}
  post-bucket: ${MINIO_POST_BUCKET}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

server:
  error:
    include-message: always
  port: 8081
